#ifndef TOSKR_KEYCHAIN_HELPER_CONFIG_H
#define TOSKR_KEYCHAIN_HELPER_CONFIG_H

#define TOSKR_CLIENT_REQUIREMENT \
    "identifier \"com.toskr.app\" and certificate leaf = H\"6e960d8b61e1fc9c534e41cb812803d07e85e87b\""
#define TOSKR_HELPER_HELLO "TSKKEY01"
#define TOSKR_HELPER_HELLO_LENGTH 8
#define TOSKR_HELPER_MAX_FRAME (64 * 1024)
#define TOSKR_HELPER_MAX_AI_RECORD (32 * 1024)
#define TOSKR_HELPER_IO_TIMEOUT_SECONDS 5

#endif
