//! 剪贴板历史：500ms 轮询 NSPasteboard changeCount，新内容发给前端入库。
//!
//! 隐私三防：前台应用命中捕获排除名单跳过；剪贴板带 Concealed/AutoGenerated
//! 标记类型（密码管理器约定）跳过；功能默认关闭（设置项显式开启）。
//! 防自污染：应用自身的剪贴板写入（复制为列表 / 发送 / 还原 / 捕获合成 ⌘C）
//! 通过 `mark_self_write_count` 记录精确 changeCount，watcher 命中即忽略。

use std::sync::atomic::{AtomicI64, Ordering};
use std::time::Duration;

use serde::Serialize;
use tauri::{AppHandle, Emitter, Manager};

use crate::capture::pasteboard_change_count;
use crate::state::AppState;

pub const CLIP_EVENT: &str = "toskr://clip";

/// 文本超过此长度不收集（粘贴板里的巨型内容多为文件/二进制转储）。
const MAX_TEXT_BYTES: usize = 100 * 1024;
const POLL: Duration = Duration::from_millis(500);

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ClipPayload {
    pub content_kind: String,
    pub text: String,
    pub image_file: Option<String>,
    pub image_w: Option<u32>,
    pub image_h: Option<u32>,
    pub app_name: Option<String>,
    pub bundle_id: Option<String>,
}

fn store_self_write_count(counter: &AtomicI64, exact_count: isize) {
    counter.store(exact_count as i64, Ordering::SeqCst);
}

/// 已由写事务证明的精确 generation；禁止在恢复后重新读取 current count 代替。
pub fn mark_self_write_count(app: &AppHandle, exact_count: isize) {
    if let Some(state) = app.try_state::<AppState>() {
        store_self_write_count(&state.pasteboard_self_count, exact_count);
    }
}

/// 当前 epoch 毫秒。
fn now_ms() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}

/// 剪贴板带隐私标记类型（密码管理器约定 http://nspasteboard.org）。
/// 机密（Concealed）与瞬时（AutoGenerated/Transient）分别由规则开关控制。
fn hits_privacy_types(ignore_concealed: bool, ignore_transient: bool) -> bool {
    if !ignore_concealed && !ignore_transient {
        return false;
    }
    let pb = objc2_app_kit::NSPasteboard::generalPasteboard();
    let Some(types) = pb.types() else {
        return false;
    };
    types.iter().any(|t| {
        let s = t.to_string();
        (ignore_concealed && s == "org.nspasteboard.ConcealedType")
            || (ignore_transient
                && (s == "org.nspasteboard.AutoGeneratedType"
                    || s == "org.nspasteboard.TransientType"))
    })
}

/// 常驻 watcher 线程（setup 时启动一次；开关由 AtomicBool 门控）。
pub fn spawn(app: AppHandle) {
    std::thread::spawn(move || {
        let mut last_seen = pasteboard_change_count() as i64;
        loop {
            std::thread::sleep(POLL);
            let state = app.state::<AppState>();
            if !state.clip_watch.load(Ordering::SeqCst) {
                // 关闭期间跟住计数，避免开启瞬间把陈旧内容当新变更收进来
                last_seen = pasteboard_change_count() as i64;
                continue;
            }
            // 暂停中：同样跟住计数（到期自然恢复，无需定时器）
            let pause_until = state.clip_pause_until.load(Ordering::Relaxed);
            if pause_until > 0 && now_ms() < pause_until {
                last_seen = pasteboard_change_count() as i64;
                continue;
            }
            // watcher 也必须持同一许可；单次 load(false) 与后续读取之间仍可被捕获抢入。
            // claim 失败时不推进 last_seen，许可释放后只处理最终状态。
            let Some(permit) = crate::pasteboard::try_claim(&app) else {
                continue;
            };
            let count = pasteboard_change_count() as i64;
            if count == last_seen {
                continue;
            }
            last_seen = count;
            if count == state.pasteboard_self_count.load(Ordering::SeqCst) {
                continue; // 应用自身写入
            }
            if hits_privacy_types(
                state.clip_ignore_concealed.load(Ordering::Relaxed),
                state.clip_ignore_transient.load(Ordering::Relaxed),
            ) {
                crate::diag::push(&app, "剪贴板: 隐私标记内容，跳过");
                continue;
            }
            // 复制动作发生时的前台应用即内容来源；忽略名单独立于捕获排除。
            // 刻意不按「前台是自己」跳过：自身写入已由精确 changeCount
            // changeCount 标记兜底，按 pid 拦会误杀面板前台期间落进来的外部
            // 写入——截图缩略图延迟数秒才写剪贴板，正是典型受害者。
            let front = crate::focus::frontmost_info();
            if let Some(f) = &front {
                let excluded = f
                    .bundle_id
                    .as_deref()
                    .map(|b| {
                        state
                            .clip_excluded_apps
                            .lock()
                            .unwrap()
                            .iter()
                            .any(|a| a == b)
                    })
                    .unwrap_or(false);
                if excluded {
                    crate::diag::push(
                        &app,
                        format!(
                            "剪贴板: {} 在忽略名单，跳过",
                            f.name.as_deref().unwrap_or("?")
                        ),
                    );
                    continue;
                }
            }
            let (app_name, bundle_id) =
                front.map(|f| (f.name, f.bundle_id)).unwrap_or((None, None));

            let src = app_name.clone().unwrap_or_else(|| "?".into());
            let mut clipboard = match arboard::Clipboard::new() {
                Ok(c) => c,
                Err(_) => continue,
            };
            if let Ok(text) = clipboard.get_text() {
                let trimmed = text.trim();
                if trimmed.is_empty() {
                    continue;
                }
                if text.len() > MAX_TEXT_BYTES {
                    crate::diag::push(
                        &app,
                        format!("剪贴板: 文本超限 {}KB，跳过", text.len() / 1024),
                    );
                    continue;
                }
                if pasteboard_change_count() as i64 != count {
                    continue;
                }
                drop(clipboard);
                drop(permit);
                crate::diag::push(
                    &app,
                    format!("剪贴板: 收文本 {} 字符 来自 {src}", text.chars().count()),
                );
                let _ = app.emit_to(
                    "main",
                    CLIP_EVENT,
                    ClipPayload {
                        content_kind: "text".into(),
                        text,
                        image_file: None,
                        image_w: None,
                        image_h: None,
                        app_name,
                        bundle_id,
                    },
                );
                continue;
            }
            match clipboard.get_image() {
                Ok(img) => {
                    let (width, height) = (img.width, img.height);
                    let rgba = img.bytes.into_owned();
                    if pasteboard_change_count() as i64 != count {
                        continue;
                    }
                    drop(clipboard);
                    drop(permit);
                    let (w, h) = (width as u32, height as u32);
                    match crate::storage::save_image_rgba(&app, width, height, &rgba) {
                        Ok(file) => {
                            crate::diag::push(&app, format!("剪贴板: 收图片 {w}×{h} 来自 {src}"));
                            let _ = app.emit_to(
                                "main",
                                CLIP_EVENT,
                                ClipPayload {
                                    content_kind: "image".into(),
                                    text: format!("图片 {w}×{h}"),
                                    image_file: Some(file),
                                    image_w: Some(w),
                                    image_h: Some(h),
                                    app_name,
                                    bundle_id,
                                },
                            );
                        }
                        Err(e) => {
                            crate::diag::push(&app, format!("剪贴板: 图片保存失败 {e}"));
                        }
                    }
                }
                // 既无文本也无图片（文件拷贝等特殊类型）——留痕，别当黑箱
                Err(_) => crate::diag::push(&app, "剪贴板: 变更无可读文本/图片，跳过"),
            }
        }
    });
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exact_self_generation_never_adopts_a_later_user_generation() {
        let counter = AtomicI64::new(0);
        let restored_generation = 41;
        let later_user_generation = 42;

        store_self_write_count(&counter, restored_generation);

        assert_eq!(counter.load(Ordering::SeqCst), restored_generation as i64);
        assert_ne!(counter.load(Ordering::SeqCst), later_user_generation as i64);
    }
}
