//! 剪贴板历史：500ms 轮询 NSPasteboard changeCount，新内容发给前端入库。
//!
//! 隐私三防：前台应用命中捕获排除名单跳过；剪贴板带 Concealed/AutoGenerated
//! 标记类型（密码管理器约定）跳过；功能默认关闭（设置项显式开启）。
//! 防自污染：应用自身的剪贴板写入（复制为列表 / 发送 / 还原 / 捕获合成 ⌘C）
//! 通过 `mark_self_write` 记录 changeCount，watcher 命中即忽略。

use std::sync::atomic::Ordering;
use std::time::Duration;

use serde::Serialize;
use tauri::{AppHandle, Emitter, Manager};

use crate::capture::pasteboard_change_count;
use crate::state::AppState;

pub const CLIP_EVENT: &str = "toskr://clip";

/// 文本超过此长度不收集（粘贴板里的巨型内容多为文件/二进制转储）。
const MAX_TEXT_BYTES: usize = 100 * 1024;
const POLL: Duration = Duration::from_millis(500);

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ClipPayload {
    pub content_kind: String,
    pub text: String,
    pub image_file: Option<String>,
    pub image_w: Option<u32>,
    pub image_h: Option<u32>,
    pub app_name: Option<String>,
    pub bundle_id: Option<String>,
}

/// 应用自身写剪贴板后调用：让 watcher 忽略这次变更。
pub fn mark_self_write(app: &AppHandle) {
    if let Some(state) = app.try_state::<AppState>() {
        state
            .pasteboard_self_count
            .store(pasteboard_change_count() as i64, Ordering::SeqCst);
    }
}

/// 剪贴板带隐私标记类型（密码管理器约定 http://nspasteboard.org）。
fn has_concealed_type() -> bool {
    let pb = objc2_app_kit::NSPasteboard::generalPasteboard();
    let Some(types) = pb.types() else {
        return false;
    };
    types.iter().any(|t| {
        let s = t.to_string();
        s == "org.nspasteboard.ConcealedType" || s == "org.nspasteboard.AutoGeneratedType"
    })
}

/// 常驻 watcher 线程（setup 时启动一次；开关由 AtomicBool 门控）。
pub fn spawn(app: AppHandle) {
    std::thread::spawn(move || {
        let mut last_seen = pasteboard_change_count() as i64;
        loop {
            std::thread::sleep(POLL);
            let state = app.state::<AppState>();
            if !state.clip_watch.load(Ordering::SeqCst) {
                // 关闭期间跟住计数，避免开启瞬间把陈旧内容当新变更收进来
                last_seen = pasteboard_change_count() as i64;
                continue;
            }
            let count = pasteboard_change_count() as i64;
            if count == last_seen {
                continue;
            }
            last_seen = count;
            if count == state.pasteboard_self_count.load(Ordering::SeqCst) {
                continue; // 应用自身写入
            }
            if has_concealed_type() {
                continue;
            }
            // 复制动作发生时的前台应用即内容来源
            let front = crate::focus::frontmost_info();
            if let Some(f) = &front {
                if f.pid == std::process::id() as i32 {
                    continue;
                }
                let excluded = f
                    .bundle_id
                    .as_deref()
                    .map(|b| state.excluded_apps.lock().unwrap().iter().any(|a| a == b))
                    .unwrap_or(false);
                if excluded {
                    continue;
                }
            }
            let (app_name, bundle_id) = front
                .map(|f| (f.name, f.bundle_id))
                .unwrap_or((None, None));

            let mut clipboard = match arboard::Clipboard::new() {
                Ok(c) => c,
                Err(_) => continue,
            };
            if let Ok(text) = clipboard.get_text() {
                let trimmed = text.trim();
                if trimmed.is_empty() || text.len() > MAX_TEXT_BYTES {
                    continue;
                }
                let _ = app.emit_to(
                    "main",
                    CLIP_EVENT,
                    ClipPayload {
                        content_kind: "text".into(),
                        text,
                        image_file: None,
                        image_w: None,
                        image_h: None,
                        app_name,
                        bundle_id,
                    },
                );
                continue;
            }
            if let Ok(img) = clipboard.get_image() {
                let (w, h) = (img.width as u32, img.height as u32);
                if let Ok(file) =
                    crate::storage::save_image_rgba(&app, img.width, img.height, &img.bytes)
                {
                    let _ = app.emit_to(
                        "main",
                        CLIP_EVENT,
                        ClipPayload {
                            content_kind: "image".into(),
                            text: format!("图片 {w}×{h}"),
                            image_file: Some(file),
                            image_w: Some(w),
                            image_h: Some(h),
                            app_name,
                            bundle_id,
                        },
                    );
                }
            }
        }
    });
}
