use std::collections::HashMap;
use std::sync::atomic::{AtomicBool, AtomicI64, AtomicU16, AtomicU64, AtomicU8};
use std::sync::Mutex;

/// 触发修饰键编码（AtomicU8）。
pub const MOD_SHIFT: u8 = 0;
pub const MOD_CONTROL: u8 = 1;
pub const MOD_OPTION: u8 = 2;

/// 伴随停靠配置（由前端 settings 下发；下发前用与前端一致的默认值，
/// 避免启动初期存在「伴随未启用」的窗口期）。
#[derive(Clone)]
pub struct CompanionConfig {
    pub enabled: bool,
    pub apps: Vec<String>,
    /// 磁吸方向：0=右（默认，贴目标窗口右缘）1=左（贴左缘），与
    /// `sidebar_edge` 同一套编码，对应用户在停靠菜单选择的 靠左/靠右。
    pub side: u8,
}

/// 与前端 DEFAULT_COMPANION_APPS 保持一致的预置伴随应用。
pub const DEFAULT_COMPANION_APPS: &[&str] = &[
    "com.apple.Terminal",
    "com.googlecode.iterm2",
    "dev.warp.Warp-Stable",
    "com.github.wez.wezterm",
    "net.kovidgoyal.kitty",
    "io.alacritty",
    "com.mitchellh.ghostty",
    "com.todesktop.230313mzl4w4u92",
    "com.microsoft.VSCode",
    "com.microsoft.VSCodeInsiders",
    "com.dimillian.codexmonitor",
    "com.codepilot.app",
    "io.appmakes.otty",
    "com.openai.codex",
];

impl Default for CompanionConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            apps: DEFAULT_COMPANION_APPS.iter().map(|s| s.to_string()).collect(),
            side: 0,
        }
    }
}

/// 贴边隐藏锚点：面板处于「右缘独立停靠 / 四缘边栏」等可自动隐藏布局时的
/// 展开态矩形 + 所在屏幕物理完整边界（逻辑 pt）+ 贴靠缘。伴随磁吸 / 独立
/// 模式手动拖离右缘时清空（None），贴边隐藏轮询据此判断是否可介入。
/// 具体的滑出目标位/触边判定/展开态容差几何都是 `edge` 相关的，实现见
/// window.rs 的 `impl EdgeHideAnchor`（geometry 与状态分层：这里只存数据）。
#[derive(Clone, Copy, Debug)]
pub struct EdgeHideAnchor {
    /// 贴靠缘：0=右 1=左 2=上 3=下，与 `sidebar_edge` 同一套编码。
    /// 独立模式（非边栏）恒为 0（右）。
    pub edge: u8,
    /// 展开态矩形（逻辑 pt，左上角原点）。
    pub x: f64,
    pub y: f64,
    pub w: f64,
    pub h: f64,
    /// 所在屏幕「物理完整边界」（`Monitor::position()+size()`，非
    /// work_area）：滑出目标位与触边判定都以此为准——work_area 在有菜单栏
    /// /靠边 Dock 等布局下会比物理屏幕窄，用它做判定线光标可能永远够不到
    /// （round 4 复现的「光标停在屏幕边缘也永远唤不回」）。
    pub screen_full_x: f64,
    pub screen_full_y: f64,
    pub screen_full_w: f64,
    pub screen_full_h: f64,
}

/// HUD 运行态（hover 轮询与连拍计数共享）。
#[derive(Default)]
pub struct HudRuntime {
    pub visible: bool,
    pub hovered: bool,
    /// HUD 逻辑坐标矩形（顶左原点全局 pt），供光标命中判定。
    pub rect_pt: (f64, f64, f64, f64),
    /// 连拍捕获计数（HUD 可见期内递增）。
    pub streak: u32,
}

/// 全局共享状态。
pub struct AppState {
    /// 面板弹出/触发前记录的前台应用 PID，用于「发送到对话」时归还焦点。
    pub prev_app_pid: Mutex<Option<i32>>,
    /// HUD 显示代数计数：防止早到的隐藏/轮询任务干扰新 HUD。
    pub hud_generation: AtomicU64,
    /// CGEventTap 是否安装成功（未授权辅助功能时会失败）。
    pub tap_installed: AtomicBool,
    /// tap 是否真正收到过键盘事件（Sequoia：创建成功≠事件投递，
    /// 输入监控权限缺失时事件被系统静默扣留）。
    pub key_events_seen: AtomicBool,

    // ===== v2 =====
    /// 触发修饰键（MOD_*）。
    pub hotkey_modifier: AtomicU8,
    /// 双击「抬起→抬起」最大间隔 ms。
    pub hotkey_gap_ms: AtomicU16,
    /// 隐身模式：不弹任何 HUD。
    pub stealth: AtomicBool,
    /// 面板逻辑宽度 pt。
    pub panel_width_pt: Mutex<f64>,
    /// 面板顶缘相对基准（伴随=目标窗口顶 / 经典=工作区顶+边距）的偏移 pt。
    pub panel_top_offset: Mutex<f64>,
    /// 面板高度覆盖 pt（None = 自动：伴随=同目标窗口高 / 经典=近全高）。
    /// 会话内临时值：吸附目标切换时重置为自动（高度跟随当前应用）。
    pub panel_height_pt: Mutex<Option<f64>>,
    /// 当前吸附目标 pid（用于检测目标切换以重置高度/偏移覆盖）。
    pub last_dock_pid: Mutex<Option<i32>>,
    /// 伴随停靠配置。
    pub companion: Mutex<CompanionConfig>,
    /// 伴随停靠时面板与目标窗口的间隙 pt（设置项，0=紧贴）。
    pub companion_gap: Mutex<f64>,
    /// 独立模式下用户手动拖到的位置（逻辑 pt，左上角）。
    pub panel_free_pos: Mutex<Option<(f64, f64)>>,
    /// 当前是否处于伴随吸附状态（决定移动事件是否记为手动位置）。
    pub docked: AtomicBool,
    /// 捕获排除列表（bundle id）：这些应用内双击只开关面板、绝不捕获。
    pub excluded_apps: Mutex<Vec<String>>,
    /// 伴随跟随任务代数（bump 即停止旧任务）。
    pub companion_gen: AtomicU64,
    /// HUD 运行态。
    pub hud: Mutex<HudRuntime>,
    /// 应用图标缓存：bundle id → (data URL, 主色)。
    pub icon_cache: Mutex<HashMap<String, Option<(String, String)>>>,
    /// 上次捕获尝试结束时的剪贴板文本快照（「新鲜度兜底」判定用：
    /// 流式终端选区被新输出冲掉时，copy-on-select 已入剪贴板的内容仍可捕获）。
    pub last_clipboard_text: Mutex<Option<String>>,
    /// 剪贴板历史收集开关（设置项下发；watcher 线程常驻按此门控）。
    pub clip_watch: AtomicBool,
    /// 应用自身最近一次写剪贴板后的 changeCount（watcher 忽略该次变更）。
    pub pasteboard_self_count: AtomicI64,
    /// 剪贴板规则：忽略机密内容（ConcealedType）。
    pub clip_ignore_concealed: AtomicBool,
    /// 剪贴板规则：忽略瞬时内容（AutoGenerated/Transient）。
    pub clip_ignore_transient: AtomicBool,
    /// 剪贴板规则：忽略应用列表（独立于捕获排除名单）。
    pub clip_excluded_apps: Mutex<Vec<String>>,
    /// 暂停剪贴板收集到该时刻（epoch ms；0 = 未暂停）。
    pub clip_pause_until: AtomicI64,
    /// 捕获音效开关（隐身模式下强制静音）。
    pub sound_enabled: AtomicBool,
    /// 边栏模式：面板贴屏幕某缘（保留停靠间距），与伴随磁吸互斥。
    pub right_sidebar: AtomicBool,
    /// 边栏停靠缘：0=右 1=左 2=上 3=下（左右全高竖栏，上下全宽横栏）。
    pub sidebar_edge: AtomicU8,
    /// 面板置顶偏好（用户设置）；伴随磁吸期间强制同层级，脱离后按此恢复。
    pub panel_topmost: AtomicBool,
    /// 双击触发仅捕获（面板开关完全交给专用快捷键）。
    pub double_tap_capture_only: AtomicBool,
    /// 自动贴边隐藏开关（设置项，默认关闭）：面板贴右缘时鼠标离开自动滑出，
    /// 移到屏幕右缘唤回（类似 Dock）。
    pub auto_edge_hide: AtomicBool,
    /// 面板固定（图钉）：前端 uiStore.pinned 同步。语义严格是「失焦不隐藏」，
    /// 只豁免焦点驱动的收起，不影响光标驱动的贴边隐藏。
    pub panel_pinned: AtomicBool,
    /// 用户正在拖拽面板宽度/上下缘：拖拽期间暂停贴边滑出计时。
    pub panel_dragging: AtomicBool,
    /// 面板当前是否处于贴边隐藏（滑出仅露出边缘细条）态。
    pub edge_hidden: AtomicBool,
    /// 贴边隐藏动画代数：bump 即抢占/取消正在进行的滑出滑回动画
    /// （面板重新定位、显式隐藏、设置关闭等都会抢占）。
    pub edge_hide_gen: AtomicU64,
    /// 贴边隐藏锚点（见 [`EdgeHideAnchor`]）。
    pub edge_hide_anchor: Mutex<Option<EdgeHideAnchor>>,
    /// 「机器驱动移动」截止时间戳（epoch ms，0 = 当前无机器移动）。
    /// 程序自己摆放面板（停靠/边栏/伴随重定位/改宽度/贴边滑出滑回动画）
    /// 同样会触发 `WindowEvent::Moved`，必须在此窗口期内让 lib.rs 的 Moved
    /// 处理器忽略「记为用户手动拖拽位置」的副作用。
    ///
    /// 只盖动画曾是个大坑：经典右缘自动停靠每次显示都 `set_position` 到
    /// 自己算出的位置，那一帧 Moved 把该位置写进 `panel_free_pos`，下次显示
    /// 就被判成「用户手动拖离右缘」→ 清空贴边隐藏锚点 → 贴边隐藏整体失效
    /// （用户实测：反复开关面板，日志里一条「锚点建立」都没有）。
    pub machine_move_until_ms: AtomicI64,
    /// 唤回重臂锁：滑出瞬间光标已经停在触边判定区（如失焦触发滑出时，
    /// 光标本来就停在屏幕边缘）会置位；置位期间触边判定不放行，必须等
    /// 光标先离开判定区一次才解除，避免「隐藏了又立刻被自己的光标唤回」
    /// 的抖动（round 6）。
    pub edge_hide_wake_rearm: AtomicBool,
}

impl Default for AppState {
    fn default() -> Self {
        Self {
            prev_app_pid: Mutex::new(None),
            hud_generation: AtomicU64::new(0),
            tap_installed: AtomicBool::new(false),
            key_events_seen: AtomicBool::new(false),
            hotkey_modifier: AtomicU8::new(MOD_SHIFT),
            hotkey_gap_ms: AtomicU16::new(400),
            stealth: AtomicBool::new(false),
            panel_width_pt: Mutex::new(380.0),
            panel_top_offset: Mutex::new(0.0),
            panel_height_pt: Mutex::new(None),
            last_dock_pid: Mutex::new(None),
            companion: Mutex::new(CompanionConfig::default()),
            companion_gap: Mutex::new(8.0),
            panel_free_pos: Mutex::new(None),
            docked: AtomicBool::new(false),
            excluded_apps: Mutex::new(
                [
                    "com.1password.1password",
                    "com.agilebits.onepassword7",
                    "com.bitwarden.desktop",
                    "com.apple.Passwords",
                    "com.apple.keychainaccess",
                ]
                .iter()
                .map(|s| s.to_string())
                .collect(),
            ),
            companion_gen: AtomicU64::new(0),
            hud: Mutex::new(HudRuntime::default()),
            icon_cache: Mutex::new(HashMap::new()),
            last_clipboard_text: Mutex::new(None),
            clip_watch: AtomicBool::new(false),
            pasteboard_self_count: AtomicI64::new(0),
            clip_ignore_concealed: AtomicBool::new(true),
            clip_ignore_transient: AtomicBool::new(true),
            // 前端设置下发前的兜底：与捕获排除同一批密码管理器
            clip_excluded_apps: Mutex::new(
                [
                    "com.1password.1password",
                    "com.agilebits.onepassword7",
                    "com.bitwarden.desktop",
                    "com.apple.Passwords",
                    "com.apple.keychainaccess",
                ]
                .iter()
                .map(|s| s.to_string())
                .collect(),
            ),
            clip_pause_until: AtomicI64::new(0),
            sound_enabled: AtomicBool::new(true),
            right_sidebar: AtomicBool::new(false),
            sidebar_edge: AtomicU8::new(0),
            panel_topmost: AtomicBool::new(true),
            double_tap_capture_only: AtomicBool::new(false),
            auto_edge_hide: AtomicBool::new(false),
            panel_pinned: AtomicBool::new(false),
            panel_dragging: AtomicBool::new(false),
            edge_hidden: AtomicBool::new(false),
            edge_hide_gen: AtomicU64::new(0),
            edge_hide_anchor: Mutex::new(None),
            machine_move_until_ms: AtomicI64::new(0),
            edge_hide_wake_rearm: AtomicBool::new(false),
        }
    }
}
